import { useMutation, useQueryClient } from "@tanstack/react-query"
import { z } from "zod"
import { AppToast, BoundFormField, FormItem, FormLabel, FormMessage, Input } from "@dropx/ui"

import { ReferenceCombobox } from "@/components/reference-combobox"
import { FormSheet } from "@/components/form-sheet"
import { createTransfer, updateTransfer } from "@/lib/endpoints"
import { createTransferSchema, updateTransferSchema, type UpdateTransferBody } from "@/lib/types"
import type { TransferWithManifest } from "@/lib/types"

const BLANK: z.infer<typeof createTransferSchema> = {
  fromHubId: "",
  toHubId: "",
  routeId: null,
  vehicleId: null,
  driverRef: null,
}

/**
 * Plan a hub-to-hub run.
 *
 * Both hubs are required — a transfer is defined by its two ends, unlike a pickup
 * which inherits its hub from the parcel. `driverRef` is a **staff** member's id
 * or email rather than a rider: rule 9 makes transfer drivers staff, and there is
 * no staff directory endpoint to pick from, so the one string a dispatcher
 * actually has is their email.
 *
 * There is no status field. A new transfer is always `PLANNED`, and the API's
 * create body defaults it; offering the other four would mean creating a transfer
 * in a state no one can reach by the normal route.
 *
 * The edit sheet reuses this component with a narrower schema: `updateTransferSchema`
 * makes every field optional and allows nulling the three references, because
 * clearing a vehicle mid-plan is a legitimate edit.
 */
export function TransferFormSheet({
  open,
  onOpenChange,
  transfer,
}: {
  open: boolean
  onOpenChange: (open: boolean) => void
  /** Present when editing, absent when creating. */
  transfer?: TransferWithManifest | null
}) {
  const queryClient = useQueryClient()
  const isEdit = Boolean(transfer)

  const mutation = useMutation({
    mutationFn: (body: UpdateTransferBody) =>
      isEdit ? updateTransfer(transfer!.id, body) : createTransfer(body),
    onSuccess: () => {
      AppToast.success(isEdit ? "Transfer updated" : "Transfer planned")
      void queryClient.invalidateQueries({ queryKey: ["transfers"] })
      onOpenChange(false)
    },
  })

  const schema = isEdit ? updateTransferSchema : createTransferSchema

  const defaults: z.infer<typeof schema> = isEdit
    ? {
        fromHubId: transfer!.fromHubId,
        toHubId: transfer!.toHubId,
        routeId: transfer!.routeId,
        vehicleId: transfer!.vehicleId,
        driverRef: null,
      }
    : BLANK

  return (
    <FormSheet
      schema={schema}
      open={open}
      onOpenChange={onOpenChange}
      title={isEdit ? "Edit transfer" : "New transfer"}
      description={
        isEdit
          ? "Hubs are editable only while planned. Route, vehicle and driver stay editable until the truck departs."
          : "Plans a hub-to-hub run. The transfer number is generated by the system."
      }
      submitLabel={isEdit ? "Save transfer" : "Create transfer"}
      busy={mutation.isPending}
      defaults={defaults}
      fieldLabels={{
        fromHubId: "Origin hub",
        toHubId: "Destination hub",
        routeId: "Route (optional)",
        vehicleId: "Vehicle (optional)",
        driverRef: "Driver (optional)",
      }}
      onSubmit={async (values) => {
        const typed = values as z.infer<typeof schema>
        await mutation.mutateAsync({
          fromHubId: typed.fromHubId,
          toHubId: typed.toHubId,
          routeId: typed.routeId || null,
          vehicleId: typed.vehicleId || null,
          driverRef: typed.driverRef || null,
        })
      }}
      error={null}
      renderFields={() => (
        <>
          <BoundFormField
            name="fromHubId"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Origin hub</FormLabel>
                <ReferenceCombobox
                  source="hubs"
                  placeholder="Search hubs"
                  value={field.value}
                  onChange={field.onChange}
                />
                <FormMessage />
              </FormItem>
            )}
          />
          <BoundFormField
            name="toHubId"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Destination hub</FormLabel>
                <ReferenceCombobox
                  source="hubs"
                  placeholder="Search hubs"
                  value={field.value}
                  onChange={field.onChange}
                />
                <FormMessage />
              </FormItem>
            )}
          />
          <BoundFormField
            name="routeId"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Route (optional)</FormLabel>
                <ReferenceCombobox
                  source="routes"
                  placeholder="Search routes"
                  value={field.value ?? ""}
                  onChange={(id) => field.onChange(id || null)}
                />
                <FormMessage />
              </FormItem>
            )}
          />
          <BoundFormField
            name="vehicleId"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Vehicle (optional)</FormLabel>
                <ReferenceCombobox
                  source="vehicles"
                  placeholder="Search vehicles"
                  value={field.value ?? ""}
                  onChange={(id) => field.onChange(id || null)}
                />
                <FormMessage />
              </FormItem>
            )}
          />
          {/*
            A plain text field, not a `ReferenceCombobox`. A transfer driver is a
            **staff** user (rule 9), and there is no staff directory endpoint to pick
            from — the admin app has no screen that lists `users`. So the dispatcher
            types the one string they actually have, the staff member's email, and the
            API resolves it to an id. The label says so, the same way the pickup form's
            parcel field says "tracking number or parcel id".
          */}
          <BoundFormField
            name="driverRef"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Driver (optional)</FormLabel>
                <Input placeholder="staff@example.com or the staff id" {...field} />
                <FormMessage />
              </FormItem>
            )}
          />
        </>
      )}
    />
  )
}