/**
 * Stable domain error codes.
 *
 * Clients branch on `code`; `message` is a safe, human string for banners. Add
 * codes here rather than inventing ad-hoc strings inside a feature — the
 * frontend maps unknown codes to their generic fallback.
 */
export const ERROR_CODES = {
  // --- validation & request shape ---
  VALIDATION_FAILED: "VALIDATION_FAILED",
  MALFORMED_REQUEST: "MALFORMED_REQUEST",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",

  // --- authentication ---
  UNAUTHENTICATED: "UNAUTHENTICATED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  WRONG_AUDIENCE: "WRONG_AUDIENCE",
  CONSENT_REQUIRED: "CONSENT_REQUIRED",

  // --- authorization ---
  FORBIDDEN: "FORBIDDEN",
  MISSING_PERMISSION: "MISSING_PERMISSION",
  OUT_OF_SCOPE: "OUT_OF_SCOPE",

  // --- resource lifecycle ---
  NOT_FOUND: "NOT_FOUND",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  DUPLICATE: "DUPLICATE",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  ACTIVE_ATTEMPT_EXISTS: "ACTIVE_ATTEMPT_EXISTS",
  IN_USE: "IN_USE",

  // --- customer auth ---
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_NOT_VERIFIED: "OTP_NOT_VERIFIED",
  CUSTOMER_NOT_ACTIVE: "CUSTOMER_NOT_ACTIVE",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  UNREGISTERED_USER: "UNREGISTERED_USER",

  // --- throttling ---
  RATE_LIMITED: "RATE_LIMITED",

  // --- infrastructure (never carries internal detail) ---
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  DATABASE_ERROR: "DATABASE_ERROR",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

/** Default HTTP status per code, so handlers never repeat the mapping. */
export const ERROR_STATUS: Readonly<
  Record<ErrorCode, 400 | 401 | 403 | 404 | 409 | 415 | 422 | 429 | 500 | 501 | 503>
> = {
  VALIDATION_FAILED: 422,
  MALFORMED_REQUEST: 400,
  UNSUPPORTED_MEDIA_TYPE: 415,

  UNAUTHENTICATED: 401,
  INVALID_CREDENTIALS: 401,
  TOKEN_EXPIRED: 401,
  TOKEN_INVALID: 401,
  WRONG_AUDIENCE: 401,
  CONSENT_REQUIRED: 403,

  FORBIDDEN: 403,
  MISSING_PERMISSION: 403,
  OUT_OF_SCOPE: 403,

  NOT_FOUND: 404,
  ALREADY_EXISTS: 409,
  DUPLICATE: 409,
  INVALID_STATE_TRANSITION: 409,
  ACTIVE_ATTEMPT_EXISTS: 409,
  IN_USE: 409,

  OTP_INVALID: 400,
  OTP_EXPIRED: 400,
  OTP_NOT_VERIFIED: 403,
  CUSTOMER_NOT_ACTIVE: 403,
  EMAIL_ALREADY_REGISTERED: 409,
  UNREGISTERED_USER: 404,

  RATE_LIMITED: 429,

  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  DATABASE_ERROR: 500,
  NOT_IMPLEMENTED: 501,
}
